### ISSUE TITLE
pixel format unavailable

### ISSUE THREAD

**Issue by void-robotics** [i3drobotics/deimos-ros#6]
Hello,

Trying on a normal linux machine (instead of the TX1) gives:

```
terminate called after throwing an instance of 'std::runtime_error'
   what(): pixel format unavailable
```

**Comment by jveitchmichaelis** [comment]
Hi, 

I'll try and reproduce this - can you give me a list of which steps you followed to install the camera? Ideally from a clean system.

Cheers!

**Comment by void-robotics** [comment]
On a Ubuntu 16.04:
1. plugged camera in
2. cloned this repo into catkin_ws/src
3. installed dependencies in README
4. roslaunch deimos deimos.launch

**Comment by jveitchmichaelis** [comment]
Ok, when I have some time I'll try on a clean ROS install. It may be worth
experimenting with something like Docker to keep things repeatable.

**Comment by jveitchmichaelis** [comment]
@nathangeorge1 Is this also related to the issue that got fixed with a clean install, or something separate?

**Comment by void-robotics** [comment]
likely something separate but I'll check

**Comment by void-robotics** [comment]
even with copying the udev rules and doing a clean install, this error persists

**Comment by jveitchmichaelis** [comment]
Can you open the camera in eg. Opencv? Or something other than ROS?

**Comment by void-robotics** [comment]
I was able to open it using the e-con Windows utility

**Comment by jveitchmichaelis** [comment]
Could you try with qv4l2? (`sudo apt install qv4l2`) 

That should help isolate if it's a problem with ros/libuvc or if you're missing a driver perhaps. Clearly the camera itself is fine, but we need to check on the same machine/OS you're having issues with.

**Comment by void-robotics** [comment]
I seem to have the latest version already

**Comment by benknight135** [comment]
This issue can sometimes happen if the wrong device is selected by the driver (for example a built in webcam).
The device to use can be defined in the launch file using the 'device' parameter:
```bash
roslaunch i3dr_deimos deimos.launch device:=/dev/video1
```
